#!/usr/bin/env bash
# Regenerates db/sample/catalog.sql: the schema plus the sample catalog
# (db/sample/catalog.json), as one script for an empty database.
#
#   db/sample/build.sh                 # uses build/*/src/caelitus
#   CAELITUS_BIN=/path/to/caelitus db/sample/build.sh
#
# The data goes through the real server, so every rule applies (normalized
# tags, rating totals, ...):
#   1. a throwaway MariaDB container;
#   2. the caelitus server on it, on a spare port, without MQTT;
#   3. web/scripts/seed.ts loads catalog.json through the JSON-RPC API;
#   4. mariadb-dump of the data, after `caelitus --schema`.
# The like history is not dumped: reaction-history.sql recreates it at load
# time relative to that day.
#
# Needs: docker, node (npm install done in web/), a built server.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
out="$here/catalog.sql"
container="caelitus-sample-build"
db_port=3399
rpc_port=9399
password="sample"

bin="${CAELITUS_BIN:-}"
if [[ -z "$bin" ]]; then
    for candidate in "$root"/build/{release,debug,asan}/src/caelitus; do
        [[ -x "$candidate" ]] && bin="$candidate" && break
    done
fi
[[ -x "$bin" ]] || { echo "No caelitus binary; build one (cmake --build --preset release) or set CAELITUS_BIN" >&2; exit 1; }

work="$(mktemp -d)"
server_pid=""
cleanup() {
    [[ -n "$server_pid" ]] && kill "$server_pid" 2>/dev/null && wait "$server_pid" 2>/dev/null || true
    docker rm -f "$container" >/dev/null 2>&1 || true
    rm -rf "$work"
}
trap cleanup EXIT

echo "==> Starting a throwaway MariaDB on port $db_port"
docker rm -f "$container" >/dev/null 2>&1 || true
docker run -d --rm --name "$container" -p "127.0.0.1:$db_port:3306" \
    -e MARIADB_ROOT_PASSWORD="$password" -e MARIADB_DATABASE=caelitus mariadb:11 >/dev/null
for _ in $(seq 60); do
    docker exec "$container" mariadb -uroot -p"$password" -e "SELECT 1" >/dev/null 2>&1 && break
    sleep 1
done

echo "==> Starting caelitus ($bin) on port $rpc_port"
cat >"$work/config.json" <<EOF
{
  "mqtt": { "server": "127.0.0.1", "port": 1, "clientId": "caelitus-sample-build" },
  "db": { "host": "127.0.0.1", "port": $db_port, "user": "root", "password": "$password", "database": "caelitus" },
  "server": { "port": $rpc_port, "bindAddress": "127.0.0.1" },
  "log": { "level": "warn", "levels": { "mqtt": "off", "mqtt.lib": "off" } }
}
EOF
"$bin" --config "$work/config.json" >"$work/server.log" 2>&1 &
server_pid=$!
for _ in $(seq 30); do
    (exec 3<>"/dev/tcp/127.0.0.1/$rpc_port") 2>/dev/null && break
    kill -0 "$server_pid" 2>/dev/null || { cat "$work/server.log" >&2; exit 1; }
    sleep 1
done

echo "==> Loading db/sample/catalog.json through the API"
(
    cd "$root/web"
    command -v npx >/dev/null || { [[ -s "$HOME/.nvm/nvm.sh" ]] && source "$HOME/.nvm/nvm.sh"; }
    CAELITUS_RPC_PORT="$rpc_port" npx tsx scripts/seed.ts
)

kill "$server_pid" && wait "$server_pid" 2>/dev/null || true
server_pid=""

echo "==> Writing $out"
{
    echo "-- caelitus sample catalog: the schema and $(jq '.books | length' "$here/catalog.json" 2>/dev/null || echo 'several hundred') real books."
    echo "-- Generated by db/sample/build.sh from db/sample/catalog.json; do not edit."
    echo "--"
    echo "-- Load into an EMPTY database (the server would otherwise create the schema itself):"
    echo "--   mariadb -u caelitus -p caelitus < db/sample/catalog.sql"
    echo "-- or, with the development container (dev/docker-compose.yml):"
    echo "--   docker exec -i caelitus-mariadb mariadb -ucaelitus -pcaelitus-dev caelitus < db/sample/catalog.sql"
    echo
    echo "SET NAMES utf8mb4;"
    echo "SET time_zone = '+00:00';"
    echo
    "$bin" --schema | sed '1,/^$/d'
    echo
    echo "-- ---- sample data ------------------------------------------------------------"
    echo
    dump() {
        docker exec "$container" mariadb-dump -uroot -p"$password" caelitus \
            --no-create-info --skip-triggers --compact --complete-insert --order-by-primary \
            --net-buffer-length=16384 "$@"
    }
    dump categories authors tags
    # books.reaction_score is a generated column, which INSERT must not name:
    # dump a copy without it under the real table name.
    docker exec "$container" mariadb -uroot -p"$password" caelitus -e \
        "CREATE TABLE books_export AS SELECT * FROM books; ALTER TABLE books_export DROP COLUMN reaction_score"
    dump books_export | sed 's/^INSERT INTO `books_export`/INSERT INTO `books`/'
    dump book_authors book_tags reviews
    echo
    cat "$here/reaction-history.sql"
} >"$out"

echo "==> Checking that the script loads into an empty database"
docker exec "$container" mariadb -uroot -p"$password" -e "DROP DATABASE caelitus; CREATE DATABASE caelitus"
docker exec -i "$container" mariadb -uroot -p"$password" caelitus <"$out"
docker exec "$container" mariadb -uroot -p"$password" caelitus -N -e \
    "SELECT CONCAT(COUNT(*), ' books, ', SUM(reactions_enabled), ' accepting likes, ',
            (SELECT COUNT(*) FROM reviews), ' reviews, ', SUM(likes), ' likes, ', SUM(dislikes), ' dislikes')
     FROM books"
echo "==> Done: $out ($(wc -c <"$out") bytes)"
