/// @file
/// Command line entry point of the caelitus server.
/// @ingroup app

#include "app/Application.hpp"

#include "caelitus/Version.hpp"
#include "caelitus/api/CatalogApi.hpp"
#include "caelitus/api/OpenRpc.hpp"
#include "caelitus/api/OperationsApi.hpp"
#include "caelitus/catalog/mariadb/CatalogMigrations.hpp"
#include "caelitus/cli/Cli.hpp"
#include "caelitus/db/DbErrors.hpp"
#include "caelitus/db/Migrations.hpp"
#include "caelitus/net/TcpServer.hpp"

#include <csignal>
#include <iostream>
#include <string>
#include <vector>

namespace {

using namespace caelitus;

constexpr const char* kUsage = R"(Usage: caelitus [options]
       caelitus --cli [client options] [<method> [parameters...]]

Runs the caelitus book catalog server: JSON-RPC 2.0 over TCP, MariaDB storage,
likes/dislikes over MQTT.

Options:
  --cli ...         Do not start a server: connect to a running one and call a
                    method (caelitus --cli --help for its options).
  --config <file>   Configuration file. Default: $CAELITUS_CONFIG, then
                    ./config/config.json, then config/config.json in the
                    executable's directory or any directory above it.
  --openrpc         Print the API description (OpenRPC JSON) and exit.
  --schema          Print the database schema (SQL) and exit.
  --version         Print the version and exit.
  --help            Print this help and exit.

Environment:
  Any "${NAME}" string in the configuration is read from environment variable
  NAME, e.g. "password": "${CAELITUS_DB_PASSWORD}".

Exit codes: 0 clean stop, 1 runtime error, 2 bad usage or configuration.
)";

bool hasFlag(int argc, char** argv, const char* flag) {
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == flag) return true;
    return false;
}

// Blocks SIGINT/SIGTERM in every thread (threads inherit the mask, so this
// runs before any thread starts); the main thread then waits for them with
// sigwait() instead of handling them asynchronously.
sigset_t blockShutdownSignals() {
    sigset_t set;
    sigemptyset(&set);
    sigaddset(&set, SIGINT);
    sigaddset(&set, SIGTERM);
    pthread_sigmask(SIG_BLOCK, &set, nullptr);
    return set;
}

}  // namespace

/// Parses the command line, loads the configuration, runs app::Application
/// until SIGINT/SIGTERM, then stops it gracefully. With `--cli`, runs the
/// command-line client (cli::run()) instead.
/// @return 0 after a clean stop, 1 on a runtime error, 2 for bad usage or configuration
///         (`--cli`: see cli::ExitCode).
int main(int argc, char** argv) {
    // Client mode: every other argument belongs to the client.
    for (int i = 1; i < argc; ++i) {
        if (std::string(argv[i]) != "--cli") continue;
        std::vector<std::string> args(argv + 1, argv + argc);
        args.erase(args.begin() + (i - 1));
        return cli::run(args, std::cout, std::cerr);
    }

    // Commands that need no configuration.
    if (hasFlag(argc, argv, "--help")) return std::cout << kUsage, 0;
    if (hasFlag(argc, argv, "--version")) return std::cout << "caelitus " << kVersion << "\n", 0;
    if (hasFlag(argc, argv, "--openrpc")) {
        api::JsonRpcHandler rpc;
        api::registerCatalogApi(rpc, {});
        api::registerOperationsApi(rpc, nullptr, nullptr);
        std::cout << api::openRpcDocument(rpc, api::catalogApiInfo()).dump(2) << "\n";
        return 0;
    }
    if (hasFlag(argc, argv, "--schema")) {
        std::cout << "-- caelitus " << kVersion << " database schema. Generated by `caelitus --schema`; do not edit.\n"
                  << "-- Load into an empty database: mariadb <database> < db/schema.sql\n\n"
                  << db::MigrationRunner::toSql(catalog::mariadb::catalogMigrations());
        return 0;
    }
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--config") ++i;
        else if (arg.rfind("--config=", 0) != 0) return std::cerr << "Unknown option " << arg << "\n\n" << kUsage, 2;
    }

    const sigset_t shutdownSignals = blockShutdownSignals();

    AppConfig config;
    try {
        const auto path = AppConfig::locate(argc, argv);
        config = AppConfig::load(path);
        log::init(config.log);
        log::get("app")->info("caelitus {} starting; configuration from {}", kVersion, path.string());
    } catch (const std::exception& e) {
        std::cerr << "Configuration error: " << e.what() << "\n";  // logging is not set up yet
        return 2;
    }

    auto log = log::get("app");
    int exitCode = 0;
    try {
        app::Application application(std::move(config));
        application.start();
        log->info("Ctrl+C or SIGTERM to stop");
        int signal = 0;
        sigwait(&shutdownSignals, &signal);
        log->info("Received {}, shutting down", signal == SIGINT ? "SIGINT" : "SIGTERM");
        application.stop();
    } catch (const ConfigError& e) {
        log->error("Configuration error: {}", e.what());
        exitCode = 2;
    } catch (const net::NetError& e) {
        log->error("Server error: {}", e.what());
        exitCode = 1;
    } catch (const db::DatabaseError& e) {
        log->error("Database error: {}", e.what());
        exitCode = 1;
    } catch (const std::exception& e) {
        log->critical("Fatal error: {}", e.what());
        exitCode = 1;
    }
    log::shutdown();
    return exitCode;
}
